services:
  # Quarkus native application for amd64
  # The image is built using GitHub Actions and pushed to Docker Hub
  # The Docker Hub image available at https://hub.docker.com/r/amusarra/quarkus-graphql-quickstart-native/
  # The value of the APP_KEYSTORE_PATH environment variable must be set
  # by command line export APP_KEYSTORE_PATH=$(pwd)/src/main/resources/app-keystore.p12
  # The value of the APP_KEYSTORE_PASSWORD environment variable must be set
  # equals to value defined in the application.properties file.
  quarkus-app:
    image: amusarra/quarkus-graphql-quickstart-native:latest-amd64
    container_name: quarkus-graphql-native-amd64
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ${APP_KEYSTORE_PATH}:/security/keystore/app-keystore.p12
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/quarkus
      - QUARKUS_DATASOURCE_USERNAME=quarkus
      - QUARKUS_DATASOURCE_PASSWORD=quarkus
      - QUARKUS_MINIO_URL=http://minio:9090
      - QUARKUS_MINIO_ACCESS_KEY=minioadmin
      - QUARKUS_MINIO_SECRET_KEY=minioadmin
      - APP_KEYSTORE_PASSWORD=YXBwLWtleXN0b3JlLnAxMg==
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9090:9090"

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: quarkus
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quarkus"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio-storage
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data: