name: CI build-publish container native image with Quarkus CLI

on:
  push:
    branches:
      - develop
      - main
  release:
    types: [ published ]

jobs:
  docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm ]
        arch: [ amd64, arm64 ]
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get repo name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)" >> $GITHUB_ENV
      - name: Git ref name trigger
        run: echo ${{ github.ref_name }}
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@main
        with:
          java-version: '22-ea'
          distribution: 'graalvm'
          github-token: ${{ secrets.TOKEN_GITHUB }}
          native-image-job-reports: 'true'
      - name: Install JBang and Quarkus CLI
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - trust add https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/
          curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force quarkus@quarkusio
          echo "PATH=$PATH:/home/runner/.jbang/bin" >> $GITHUB_ENV
      - name: Verify Quarkus CLI installation
        run: quarkus --version
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build Native Image and Push Docker Image
        run: |
          quarkus image build --native \
          -Dquarkus.native.container-build=false \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.registry=docker.io \
          -Dquarkus.container-image.username=${{ secrets.DOCKER_USERNAME }} \
          -Dquarkus.container-image.image=${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ github.ref_name }}-${{ matrix.arch }}
