name: CI build-publish container native image with Quarkus CLI

on:
  push:
    branches:
      - develop
      - main
  release:
    types: [ published ]

jobs:
  docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm ]
        arch: [ amd64, arm64 ]
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get repo name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)" >> $GITHUB_ENV
      - name: Git ref name trigger
        run: echo ${{ github.ref_name }}
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'
      - name: Install JBang and Quarkus CLI
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - trust add https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/
          curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force quarkus@quarkusio
          echo "PATH=$PATH:/home/runner/.jbang/bin" >> $GITHUB_ENV
      - name: Verify Quarkus CLI installation
        run: quarkus --version
      - name: Build Native Image
        run: quarkus build --native -Dquarkus.native.container-build=true
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push Docker Image
        run: quarkus image push -Dquarkus.container-image.tag=${{ github.ref_name }}-${{ matrix.arch }}